config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :documents
  resources :responsibles

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/document.rb
class Document < ApplicationRecord
	validates :title, presence: true,
					  length: {minimum: 3, maximum: 30},
					  uniqueness: true
	validates :content, presence: true
  	belongs_to :category

  	scope :getDocumentReferences, -> { where.not(category_id: 3) }
  	scope :getRecordReferences, -> { where(category_id: 3) }
end

app/models/responsible.rb
class Responsible < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	#http_basic_authenticate_with name: "admin", password: "admin"
	def index
		@documents = Document.all
	end

	def show
		@document = Document.find(params[:id])
	end

	def new
		@document = Document.new
		@categories = Category.all
		@documentReferences = Document.getDocumentReferences
		@recordReferences = Document.getRecordReferences
		@responsibles = Responsible.all
	end

	def create
		#render plain: params[:document].inspect
		#render plain: x
		@document = Document.new(document_params)

		if @document.save
			redirect_to documents_path
		else
			@categories = Category.all
			@documentReferences = Document.getDocumentReferences
			@recordReferences = Document.getRecordReferences
			@responsibles = Responsible.all
			render 'new'
		end
	end

	def edit
		@categories = Category.all
		@documentReferences = Document.getDocumentReferences
		@recordReferences = Document.getRecordReferences
		@responsibles = Responsible.all
		@document = Document.find(params[:id])
	end

	def update
	  	@document = Document.find(params[:id])
		@categories = Category.all
		@documentReferences = Document.getDocumentReferences
		@recordReferences = Document.getRecordReferences
		@responsibles = Responsible.all
	 
	  	if @document.update(document_params)
	    	redirect_to documents_path
	  	else
	    	render 'edit'
	  	end
	end

	def destroy
	  @document = Document.find(params[:id])
	  @document.destroy
	 
	  redirect_to documents_path
	end

	private
		def document_params
			params.require(:document).permit(:title, :content, :category_id)
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/responsibles_controller.rb
class ResponsiblesController < ApplicationController
	def index
		@responsibles = Responsible.all
	end

	def new
		@responsible = Responsible.new
	end

	def create
		@responsible = Responsible.new(responsible_params)

		if @responsible.save
			redirect_to responsibles_path
		else
			render 'new'
		end
	end

	private
	def responsible_params
		params.require(:responsible).permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/responsibles_helper.rb
module ResponsiblesHelper
end

app/views/documents/_form.html.erb
<%= render 'styles' %>
<%= render 'scripts' %>
<div class="card">
	<div class="card-header">
		<%= form_with model: @document, local: true do |form| %>
			<% if @document.errors.any? %>
			    <div id="error_explanation">
			    	<ul>
				        <% @document.errors.full_messages.each do |msg| %>
				        	<div class="alert alert-danger">
				          		<li><%= msg %></li>
				      		</div>
				        <% end %>
			      	</ul>
			    </div>
			<% end %>
		 	<div class="row">
			 	<div class="col-sm-5">
			    	<%= form.label :title %><br>
			    	<%= form.text_field :title, class: "form-control" %>
				</div>
				<div class="col-sm-4">
				    <%= form.label :category_id %><br>
				    
					<%= form.collection_select(:category_id, @categories, :id, :name, {prompt: "Select a category"}, {class: "form-control"}) %>
				</div>
				<div class="col-sm-3">
					<div class="btn-group" style="margin-top: 25px; width: 100%;">
					    <%= form.submit "Save", class: "btn btn-primary", id: "save_btn", style: 'width: 50%;'  %>
					    <%= link_to 'Back', documents_path, class: "btn btn-default", :style => 'width: 50%;' %>
					</div>
				</div>
			</div>
			<div>
			    <%= form.text_area :content, class: "form-control", style: "display: none;" %>
			</div>
			<div class="text-center" style="margin: 10px 0 10px 0;"><strong>DOCUMENT EDITOR</strong></div>
		  	<div class="row" style="margin-bottom: 20px;">
		  		<div class="col-sm-4">
		  			<select class="form-control ql-insertRef">
						<option value="">Select document</option>
						<% @documentReferences.each do |reference| %>
							<option value="<%= reference.id %>" data-marker="[doc_<%= reference.id %>]" data-title="<%= reference.title %>"><%= reference.title %></option>
						<%end%>
					</select>
		  		</div>	
		  		<div class="col-sm-4">
		  			<select class="form-control ql-insertRef">
						<option value="">Select record</option>
						<% @recordReferences.each do |reference| %>
							<option value="<%= reference.id %>" data-marker="[rec_<%= reference.id %>]" data-title="<%= reference.title %>"><%= reference.title %></option>
						<%end%>
					</select>
		  		</div>	
		  		<div class="col-sm-4">
		  			<select class="form-control ql-insertRef">
						<option value="">Select responsible</option>
						<% @responsibles.each do |reference| %>
							<option value="<%= reference.id %>" data-marker="[res_<%= reference.id %>]" data-title="<%= reference.name %>"><%= reference.name %></option>
						<%end%>
					</select>
		  		</div>	
		  	</div>
		<% end %>
	</div>
	<div class="card-body">
	  	<div class="row" >
	  		<table style="width: 100%;">
	  			<thead>
	  				<th class="col-sm-4 col_toc" style="text-align: center;">
	  					<div>ACTIVITIES LIST</div>
	  				</th>
	  				<th class="col-sm-8">
			            <div id="toolbar">
			                <button id="bold-button" class="ql-bold"><i class="fa fa-bold" aria-hidden="true"></i></button>
			                <button id="italic-button" class="ql-italic"><i class="fa fa-italic" aria-hidden="true"></i></button>
			                <button id="underline-button" class="ql-underline"><i class="fa fa-underline" aria-hidden="true"></i></button>
			                <button id="align-left-button" class="ql-align" value="left" ><i class="fa fa-align-left" aria-hidden="true"></i></button>
			                <button id="align-center-button" class="ql-align" value="center"><i class="fa fa-align-center" aria-hidden="true"></i></button>
			                <button id="align-right-button" class="ql-align" value="right"><i class="fa fa-align-right" aria-hidden="true"></i></button>
			                <button id="align-justify-button" class="ql-align" value="justify"><i class="fa fa-align-justify" aria-hidden="true"></i></button>
			                <button id="activity-button"><i class="fa fa-list-alt" aria-hidden="true"></i></button>
			                <button id="link-button" class="ql-link"><i class="fa fa-link" aria-hidden="true"></i></button>
			                <button id="clean-button" class="ql-clean"><i class="fa fa-minus" aria-hidden="true"></i></button>
			                <button id="toc_hide"><i class="fa fa-minus-square" aria-hidden="true"></i></button>
			            </div>
	  				</th>
	  			</thead>
	  			<tbody>
	  				<tr>
	  					<td class="col-sm-4 col_toc" style="vertical-align: top;"><div id="toc"></div></td>
	  					<td class="col-sm-8">
							<ol style="padding: 0;">
								<div id="text_content"></div>
							</ol>
	  					</td>
	  				</tr>
	  			</tbody>
	  		</table>
		</div>
	</div>
</div>

app/views/documents/_scripts.html.erb
<% content_for :scripts do %>
<script src="/js/quill.min.js"></script>
<script src="/js/tocbot.min.js"></script>
<script type="text/javascript">
	// quilljs cdn: https://cdn.quilljs.com/1.3.6/quill.js
	// tocbot cdn: https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.1.1/tocbot.min.js
	$(document).ready(function() {
		let Embed = Quill.import('blots/embed');
		let Block = Quill.import('blots/block');
		let BlockEmbed = Quill.import('blots/block/embed');

		class TemplateMarker extends Embed {
	    	static create(value) {
		        let node = super.create(value);
		        switch(value.marker.substr(1, 3)) {
		        	case 'doc':
				        node.setAttribute('class', 'btn btn-xs btn-info');
		        		break;
		        	case 'rec':
				        node.setAttribute('class', 'btn btn-xs btn-warning');
		        		break;
		        	case 'res':
				        node.setAttribute('class', 'btn btn-xs btn-success');
				        break;
				    default:
				        node.setAttribute('class', 'btn btn-xs btn-danger');
			    }
		        node.setAttribute('data-marker', value.marker);
		        node.setAttribute('data-title', value.title);
		        node.innerHTML = value.title;
		        return node;
		    }
			static value(node) {
		        return {
		            marker: node.getAttribute('data-marker'),
		            title: node.getAttribute('data-title'),
		        };
		    }
		}
		TemplateMarker.blotName = 'TemplateMarker';
		TemplateMarker.tagName = 'span';

		class ListItemBlot extends Block {
		  static formats(node) {
		    return ListItemBlot.tagName.indexOf(node.tagName) + 1;
		  }
		}
		ListItemBlot.blotName = 'list';
		ListItemBlot.tagName = ['li'];

		Quill.register({
		    'formats/TemplateMarker': TemplateMarker
		});
		Quill.register(ListItemBlot);

		var options = {
		  	modules: {
			    toolbar: "#toolbar"
			},
			placeholder: 'Procedure details...',
			theme: 'snow'
		};

		var quill = new Quill('#text_content', options);

	   	tocbot.init({
			tocSelector: '#toc',
			contentSelector: '#text_content',
			headingSelector: 'li',
		});

		quill.on('text-change', function(delta, oldDelta, source) {
			var veditor = document.getElementById("text_content");
	        var vh1 = veditor.getElementsByTagName("li");   
	        for (i=0;i<vh1.length;i++) vh1[i].setAttribute("id", "id_"+ (i+1));
	        tocbot.refresh();
	   	});

		$('.ql-insertRef').on('change', function() {
			let range = quill.getSelection(true);
			quill.insertEmbed(
			    range.index,
			    'TemplateMarker',
			    {
					marker: $(this).find(':selected').data('marker'),
					title: $(this).find(':selected').data('title')
				},
			);
			quill.insertText(range.index + 1, ' ', Quill.sources.USER);
			quill.setSelection(range.index + 2, Quill.sources.SILENT);
			$(this).val("");
		});

		$("#activity-button").on("click", function(e) {
			e.preventDefault();
			t=undefined!=quill.getFormat().list;
			quill.format('list', !t);
	  	});

	  	$('#toc_hide').click(function(e) {
			coltoc=$(".col_toc");
			if(coltoc[0].style.display=="none") {
				coltoc.show();
			}
			else {
				coltoc.hide();
			}
			e.preventDefault();
		});
		$(window).resize(function() {
			s_height = $(window).height() - $('.ql-editor')[0].getBoundingClientRect().top + window.scrollY - 10 +'px';
			$('.ql-editor')[0].style.height = s_height;
			$('#toc')[0].style.height = s_height;
		});
		$("#save_btn").on("click", function(e) {
			$("#document_content").val(JSON.stringify(quill.getContents()));
	  	});
	  	if($("#document_content")) {
	  		try {
		  		quill.setContents(JSON.parse($("#document_content").val()));
		  	} catch(e) {
		  		$("#document_content").val("");
		  	}
	  	}
		s_height = $(window).height() - $('.ql-editor')[0].getBoundingClientRect().top + window.scrollY - 10 +'px';
		$('.ql-editor')[0].style.height = s_height;
		$('#toc')[0].style.height = s_height;
	});
</script>
<% end %>

app/views/documents/_styles.html.erb
<% content_for :stylesheets do %>
<link href="/css/quill.snow.css" rel="stylesheet">
<link href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" rel="stylesheet">
<link href="/css/tocbot.css" rel="stylesheet">
<style type="text/css">
/* 	quilljs cdn: https://cdn.quilljs.com/1.3.6/quill.snow.css 
	tocbot cdn: https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.1.1/tocbot.css
*/
.is-active-link {
	font-weight: 400;
}
.ql-container {
    border-style: none !important;
}
.ql-editor {
    /*height: auto !important;*/
	border-style: solid;
	border-color: #ccc;
	border-width: 1px;
    min-height: 100px;
    /*position: fixed;*/
    width: 100%;
    position: relative;
}
#toc {
	min-height: 100px;
	overflow-y: auto;
	border-style: solid;
	border-color: #ccc;
	border-width: 1px;
}
.toc-link::before {
	position: static;
}
#toc ol {
	margin-left: 15px;
}
.col_toc div {
	border-style: solid;
	border-color: #ccc;
	border-width: 1px;
	padding: 10px 15px;
    /*margin: 0 15px 0 15px;
    display: block;
    width: auto;*/
}
#text_content li {
	font-size: 16px !important;
	font-weight: bold;
	margin-left: 12px;
}
#text_content p {
	margin-left: 12px;
}
.ql-editor.ql-blank::before {
	margin-left: 12px;
}
.col_toc {
/*    display: inline-block; 
    position: relative; 
    float: left; */
    display: block;
}
.col_content {
/*    display: inline-block; 
    position: relative; */
    display: block;
}
</style>
<% end %>

app/views/documents/edit.html.erb
<h1>Edit document</h1>
 
<%= render 'form' %>

app/views/documents/index.html.erb
<h1>Listing documents</h1>
 
<div class="btn-group">
  <%= link_to 'New document', new_document_path, class: "btn btn-primary" %>
  <%= link_to 'Home', home_index_path, class: "btn btn-default" %>
</div>
<table class="table table-striped" style="margin-top: 20px;">
  <tr>
    <th>Title</th>
    <th>Category</th>
    <th></th>
  </tr>
 
  <% @documents.each do |document| %>
    <tr>
      <td><%= document.title %></td>
      <td><%= document.category.name %></td>
      <td>
        <%= link_to 'Show', document_path(document) %>
        <%= link_to 'Edit', edit_document_path(document) %>
        <%= link_to 'Destroy', document_path(document),
              method: :delete,
              data: { confirm: 'Are you sure?' } %> 
      </td>
    </tr>
  <% end %>
</table>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form' %>

app/views/documents/show.html.erb
<h1>Show Document</h1>
<p>
  <strong>Title:</strong>
  <div class="form-control">
  	<%= @document.title %>
  </div>
</p>
 
<p>
  <input type="hidden" id="document_content" value="<%= @document.content %>"></input>
  <strong>Content:</strong>
  <ol>
    <div id="content"></div>
  </ol>	
</p>

<p>
  <strong>Category:</strong>
  <div class="form-control">
  	<%= @document.category.name %>
  </div>
</p>
<%= link_to 'Back', documents_path, class: "btn btn-primary" %>
<script src="/js/quill.min.js"></script>
<script type="text/javascript">
    let Embed = Quill.import('blots/embed');
    let Block = Quill.import('blots/block');
    let BlockEmbed = Quill.import('blots/block/embed');

    class TemplateMarker extends Embed {
        static create(value) {
            let node = super.create(value);
            switch(value.marker.substr(1, 3)) {
              case 'doc':
                node.setAttribute('class', 'btn btn-xs btn-info');
                break;
              case 'rec':
                node.setAttribute('class', 'btn btn-xs btn-warning');
                break;
              case 'res':
                node.setAttribute('class', 'btn btn-xs btn-success');
                break;
            default:
                node.setAttribute('class', 'btn btn-xs btn-danger');
          }
            node.setAttribute('data-marker', value.marker);
            node.setAttribute('data-title', value.title);
            node.innerHTML = value.title;
            return node;
        }
      static value(node) {
            return {
                marker: node.getAttribute('data-marker'),
                title: node.getAttribute('data-title'),
            };
        }
    }
    TemplateMarker.blotName = 'TemplateMarker';
    TemplateMarker.tagName = 'span';

    class ListItemBlot extends Block {
      static formats(node) {
        return ListItemBlot.tagName.indexOf(node.tagName) + 1;
      }
    }
    ListItemBlot.blotName = 'list';
    ListItemBlot.tagName = ['li'];

    Quill.register({
        'formats/TemplateMarker': TemplateMarker
    });
    Quill.register(ListItemBlot);
    $('#content')[0].innerHTML = quillGetHTML(JSON.parse($("#document_content").val()));

    function quillGetHTML(inputDelta) {
        var tempCont = document.createElement("div");
        (new Quill(tempCont)).setContents(inputDelta);
        return tempCont.getElementsByClassName("ql-editor")[0].innerHTML;
    }
</script>

app/views/home/index.html.erb
<h1>Document Application Home</h1>

<%= link_to 'Documents Management', {controller: 'documents'}, class: "btn btn-primary" %>
<%= link_to 'Responsibles Management', {controller: 'responsibles'}, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Editor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :stylesheets %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <%= yield :scripts %>
  </body>
</html>

app/views/responsibles/_form.html.erb
<div class="card">
	<div class="card-body">
		<%= form_with model: @responsible, local: true do |form| %>

		  <% if @responsible.errors.any? %>
		    <div id="error_explanation">
		        <% @responsible.errors.full_messages.each do |msg| %>
		        	<div class="alert alert-danger">
		          		<li><%= msg %></li>
		      		</div>
		        <% end %>
		      </ul>
		    </div>
		  <% end %>

		  <p>
		    <%= form.label :name %><br>
		    <%= form.text_field :name, class: "form-control" %>
		  </p>
		 
		  <div class="btn-group">
		    <%= form.submit "Save", class: "btn btn-primary" %>
		    <%= link_to 'Back', documents_path, class: "btn btn-default" %>
		  </div>
		<% end %>
	</div>
</div>

app/views/responsibles/index.html.erb
<h1>Listing responsibles</h1>
 
<div class="btn-group">
  <%= link_to 'New responsible', new_responsible_path, class: "btn btn-primary" %>
  <%= link_to 'Home', home_index_path, class: "btn btn-default" %>
</div>
<table class="table table-striped" style="margin-top: 20px;">
  <tr>
    <th>Name</th>
    <th></th>
  </tr>
 
  <% @responsibles.each do |responsible| %>
    <tr>
      <td><%= responsible.name %></td>
      <td>
        <%= link_to 'Show', responsible_path(responsible) %>
        <%= link_to 'Edit', edit_responsible_path(responsible) %>
        <%= link_to 'Destroy', responsible_path(responsible),
              method: :delete,
              data: { confirm: 'Are you sure?' } %> 
      </td>
    </tr>
  <% end %>
</table>

app/views/responsibles/new.html.erb
<h1>New Responsible</h1>

<%= render 'form' %>